apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
  labels:
    app: jenkins-demo
spec:
  # ClusterIP: ใช้งานภายใน Cluster
  # NodePort: เปิด Port บน Node ให้เข้าถึงจากภายนอกได้ (เหมาะสำหรับการทดลอง)
  type: NodePort 
  ports:
    - port: 80 # Port ภายใน Cluster
      targetPort: 8080 # Port ที่ Container ของคุณรันอยู่ (ใน Dockerfile)
      nodePort: 30000 # Port บน Node Host (ต้องอยู่ในช่วง 30000-32767)
  selector:
    app: jenkins-demo # ต้องตรงกับ labels ใน Deployment